<malloc.h> is deprecated by POSIX and not required here
In file included from Source/GmmLib/ULT/GmmAuxTableULT.cpp:25:
In file included from Source/GmmLib/ULT/./GmmAuxTableULT.h:33:
/usr/include/malloc.h:3:2: error: "<malloc.h> has been replaced by <stdlib.h>"
 #error "<malloc.h> has been replaced by <stdlib.h>"
  ^